### ISSUE TITLE
baseURL misconfigured

### ISSUE THREAD

**Issue by kivikakk** [nektro/mlog#1]
Hello! I read your blog through RSS.

I think [`baseURL`](https://github.com/nektro/mlog/blob/1978716a934e70c6825c1e77bb92a34b04e16b64/config.toml#L1) is misconfigured — it should include the protocol+hostname ([docs](https://gohugo.io/getting-started/configuration/#all-configuration-settings)).

The [RSS feed](https://mlog.nektro.net/index.xml) should have full URLs to the posts in the `<link>` elements, but it just has relative links instead, so clicking through doesn't work. I think this is the cause.

**Comment by nektro** [comment]
good catch, thanks!

**Comment by nektro** [comment]
fixed! <https://mlog.nektro.net/index.xml> :)

**Comment by kivikakk** [comment]
Yay, thank you! <3
